// ============================================================================
// setup.mjs — единая команда `bun run setup` для новой машины.
// ============================================================================
//
// Что делает:
//   1. Проверяет .env, создаёт из .env.example если нет
//   2. Генерирует LIA_ENCRYPTION_KEY если отсутствует
//   3. Запускает `bun install` (если node_modules нет)
//   4. Запускает `bun run db:push` (Prisma schema)
//   5. Проверяет Ollama health (опционально)
//   6. Устанавливает git pre-commit hook
//   7. Выводит summary с следующими шагами
//
// Запуск:
//   bun run setup
//
// Идемпотентно — можно запускать многократно.

import { existsSync, readFileSync, writeFileSync, accessSync, mkdirSync } from 'fs';
import { execSync, spawnSync } from 'child_process';
import { randomBytes } from 'crypto';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..');

const COLORS = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  blue: '\x1b[34m',
  gray: '\x1b[90m',
};

function log(icon, msg, color = COLORS.reset) {
  console.log(`${color}${icon} ${msg}${COLORS.reset}`);
}

function step(num, msg) {
  console.log(`\n${COLORS.blue}━━━ Step ${num}: ${msg} ━━━${COLORS.reset}`);
}

function run(cmd, opts = {}) {
  try {
    return spawnSync(cmd, {
      shell: true,
      stdio: opts.silent ? 'pipe' : 'inherit',
      cwd: PROJECT_ROOT,
      ...opts,
    });
  } catch (e) {
    return { status: 1, error: e.message };
  }
}

// ============================================================================
// Step 1: .env file
// ============================================================================
function ensureEnvFile() {
  step(1, 'Checking .env file');
  const envPath = path.join(PROJECT_ROOT, '.env');
  const envExamplePath = path.join(PROJECT_ROOT, '.env.example');

  if (!existsSync(envExamplePath)) {
    log('⚠️ ', '.env.example not found — skipping .env creation', COLORS.yellow);
    return false;
  }

  if (!existsSync(envPath)) {
    const content = readFileSync(envExamplePath, 'utf-8');
    writeFileSync(envPath, content);
    log('✓', 'Created .env from .env.example', COLORS.green);
    return true;
  }

  log('✓', '.env exists', COLORS.gray);
  return true;
}

// ============================================================================
// Step 2: LIA_ENCRYPTION_KEY
// ============================================================================
function ensureEncryptionKey() {
  step(2, 'Checking LIA_ENCRYPTION_KEY');
  const envPath = path.join(PROJECT_ROOT, '.env');

  if (!existsSync(envPath)) {
    log('⚠️ ', '.env does not exist — skipping', COLORS.yellow);
    return;
  }

  let content = readFileSync(envPath, 'utf-8');

  // Check if LIA_ENCRYPTION_KEY is set (and not commented out)
  const hasKey = /^LIA_ENCRYPTION_KEY=[A-Za-z0-9+/=]+$/m.test(content);

  if (hasKey) {
    log('✓', 'LIA_ENCRYPTION_KEY is set', COLORS.green);
    return;
  }

  // Generate new key
  const key = randomBytes(32).toString('base64');
  const newContent = content + `\n# Auto-generated by setup on ${new Date().toISOString()}\nLIA_ENCRYPTION_KEY=${key}\n`;
  writeFileSync(envPath, newContent);
  log('✓', `Generated LIA_ENCRYPTION_KEY and saved to .env`, COLORS.green);
  log('⚠️ ', 'IMPORTANT: Back up your .env file — losing LIA_ENCRYPTION_KEY breaks decryption of encrypted fields at rest', COLORS.yellow);
}

// ============================================================================
// Step 3: Install dependencies
// ============================================================================
function installDependencies() {
  step(3, 'Installing dependencies');
  const nodeModulesPath = path.join(PROJECT_ROOT, 'node_modules');

  if (existsSync(nodeModulesPath)) {
    log('✓', 'node_modules exists (skipping install)', COLORS.gray);
    return;
  }

  log('⏳', 'Running bun install...', COLORS.blue);
  const result = run('bun install');
  if (result.status === 0) {
    log('✓', 'Dependencies installed', COLORS.green);
  } else {
    log('❌', 'bun install failed', COLORS.red);
    log('ℹ️ ', 'Try manually: bun install', COLORS.yellow);
  }
}

// ============================================================================
// Step 4: Database schema
// ============================================================================
function setupDatabase() {
  step(4, 'Setting up database schema');
  const result = run('bun run db:push', { silent: true });
  if (result.status === 0) {
    log('✓', 'Database schema applied', COLORS.green);
  } else {
    log('⚠️ ', 'db:push had issues (may be normal if DB already exists)', COLORS.yellow);
    console.log(result.stdout?.toString() || result.stderr?.toString() || '');
  }
}

// ============================================================================
// Step 5: Ollama health check (optional, non-blocking)
// ============================================================================
function checkOllama() {
  step(5, 'Checking Ollama (optional)');
  const baseUrl = process.env.OLLAMA_BASE_URL || 'http://127.0.0.1:11434';

  try {
    const result = spawnSync('curl', ['-s', '-o', '/dev/null', '-w', '%{http_code}', `${baseUrl}/api/tags`], {
      stdio: 'pipe',
      timeout: 5000,
    });
    const code = result.stdout?.toString().trim();

    if (code === '200') {
      log('✓', `Ollama is UP at ${baseUrl}`, COLORS.green);
    } else {
      log('⚠️ ', `Ollama returned ${code || 'no response'} at ${baseUrl}`, COLORS.yellow);
      log('ℹ️ ', 'Install: https://ollama.com  •  Start: ollama serve  •  Pull model: ollama pull qwen3:8b nomic-embed-text', COLORS.yellow);
    }
  } catch {
    log('⚠️ ', `Could not reach Ollama at ${baseUrl}`, COLORS.yellow);
    log('ℹ️ ', 'Install: https://ollama.com  •  Start: ollama serve', COLORS.yellow);
  }
}

// ============================================================================
// Step 7: Git pre-commit hook
// ============================================================================
function installGitHook() {
  step(7, 'Installing git pre-commit hook');
  const hookSource = path.join(PROJECT_ROOT, 'scripts', 'pre-commit-token-check.sh');
  const hookTarget = path.join(PROJECT_ROOT, '.git', 'hooks', 'pre-commit');

  if (!existsSync(path.join(PROJECT_ROOT, '.git'))) {
    log('⚠️ ', 'Not a git repository — skipping hook install', COLORS.gray);
    return;
  }

  if (!existsSync(hookSource)) {
    log('⚠️ ', 'pre-commit-token-check.sh not found in scripts/', COLORS.yellow);
    return;
  }

  try {
    // Copy script
    const content = readFileSync(hookSource, 'utf-8');
    mkdirSync(path.dirname(hookTarget), { recursive: true });
    writeFileSync(hookTarget, content, { mode: 0o755 });
    // chmod +x
    spawnSync('chmod', ['+x', hookTarget], { stdio: 'pipe' });
    log('✓', 'Pre-commit hook installed (.git/hooks/pre-commit)', COLORS.green);
    log('ℹ️ ', 'Hook blocks commits containing GitHub/OpenAI/AWS/Slack/Stripe tokens', COLORS.gray);
  } catch (e) {
    log('⚠️ ', `Failed to install hook: ${e.message}`, COLORS.yellow);
  }
}

// ============================================================================
// Summary
// ============================================================================
function showSummary() {
  console.log(`\n${COLORS.blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLORS.reset}`);
  console.log(`${COLORS.green}✓ Setup complete!${COLORS.reset}\n`);
  console.log('Next steps:');
  console.log('  1. Start dev server:    bun run dev');
  console.log('  2. Open:                http://localhost:3000');
  console.log('  3. Configure LLM:       Settings → Model (or use defaults)');
  console.log('  4. Add KB sources:      Settings → Knowledge Base');
  console.log('  5. Run tests:           bun run test:ci');
  console.log('');
  console.log('Useful commands:');
  console.log('  bun run dev             — start dev server');
  console.log('  bun run test:ci         — vitest (CI gate)');
  console.log('  bun run test:safe:local — стоп :3000 → тесты → restart');
  console.log('  bun run kb:backup       — create atomic DB backup');
  console.log('  bun run diagnose        — system diagnostics');
  console.log('');
  console.log(`${COLORS.gray}Documentation: README.md · docs/ARCHITECTURE.md · docs/kb/${COLORS.reset}`);
  console.log(`${COLORS.blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLORS.reset}`);
}

// ============================================================================
// Main
// ============================================================================
console.log(`${COLORS.blue}╔═══════════════════════════════════════════════════════════╗${COLORS.reset}`);
console.log(`${COLORS.blue}║          Lia v2 — Setup Wizard                            ║${COLORS.reset}`);
console.log(`${COLORS.blue}╚═══════════════════════════════════════════════════════════╝${COLORS.reset}`);

try {
  ensureEnvFile();
  ensureEncryptionKey();
  installDependencies();
  setupDatabase();
  checkOllama();
  installGitHook();
  showSummary();
} catch (e) {
  console.log(`\n${COLORS.red}❌ Setup failed: ${e.message}${COLORS.reset}`);
  console.log(e.stack);
  process.exit(1);
}
